[package]
authors = ["Domichain Maintainers <maintainers@domichain.foundation>"]
edition = "2021"
name = "domichain-sys-tuner"
description = "The domichain cluster system tuner daemon"
version = "1.11.1"
repository = "https://github.com/domichain-labs/domichain"
license = "Apache-2.0"
homepage = "https://domichain.com/"
documentation = "https://docs.rs/domichain-sys-tuner"
publish = true

[dependencies]
clap = "2.33.1"
libc = "0.2.126"
log = "0.4.17"
domichain-logger = { path = "../logger", version = "=1.11.1" }
domichain-version = { path = "../version", version = "=1.11.1" }

[target."cfg(unix)".dependencies]
unix_socket2 = "0.5.4"
users = "0.10.0"
nix = "0.24.0"
sysctl = "0.4.4"

[lib]
name = "domichain_sys_tuner"

[[bin]]
name = "domichain-sys-tuner"
path = "src/main.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
