[package]
name = "domichain-config-program"
version = "1.11.1"
description = "Domichain Config program"
authors = ["Domichain Maintainers <maintainers@domichain.foundation>"]
repository = "https://github.com/domichain-labs/domichain"
license = "Apache-2.0"
homepage = "https://domichain.com/"
documentation = "https://docs.rs/domichain-config-program"
edition = "2021"

[dependencies]
bincode = "1.3.3"
chrono = { version = "0.4.11", features = ["serde"] }
serde = "1.0.137"
serde_derive = "1.0.103"
domichain-program-runtime = { path = "../../program-runtime", version = "=1.11.1" }
domichain-sdk = { path = "../../sdk", version = "=1.11.1" }

[dev-dependencies]
domichain-logger = { path = "../../logger", version = "=1.11.1" }

[lib]
crate-type = ["lib"]
name = "domichain_config_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
