[package]
authors = ["Domichain Maintainers <maintainers@domichain.foundation>"]
edition = "2021"
name = "domichain-net-shaper"
description = "The domichain cluster network shaping tool"
version = "1.11.1"
repository = "https://Domino-Blockchain/domichain"
license = "Apache-2.0"
homepage = "https://domichain.com/"
publish = false

[dependencies]
rand = "0.7.0"
clap = { version = "3.1.5", features = ["cargo"] }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
domichain-logger = { path = "../logger", version = "=1.11.1" }

[[bin]]
name = "domichain-net-shaper"
path = "src/main.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
