[package]
name = "domichain-sdk-macro"
description = "Domichain SDK Macro"
documentation = "https://docs.rs/domichain-sdk-macro"
version = "1.16.1"
edition = "2021"
# version = { workspace = true }
# authors = { workspace = true }
# repository = { workspace = true }
# homepage = { workspace = true }
# license = { workspace = true }
# edition = { workspace = true }

[lib]
proc-macro = true

[dependencies]
bs58 = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
rustversion = { workspace = true }
syn = { workspace = true, features = ["full", "extra-traits"] }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
