[package]
name = "domichain-sdk-macro"
version = "1.11.1"
description = "Domichain SDK Macro"
authors = ["Domichain Maintainers <maintainers@domichain.foundation>"]
repository = "https://github.com/domichain-labs/domichain"
homepage = "https://domichain.com/"
documentation = "https://docs.rs/domichain-sdk-macro"
license = "Apache-2.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
bs58 = "0.4.0"
proc-macro2 = "1.0.19"
quote = "1.0"
syn = { version = "1.0", features = ["full", "extra-traits"] }
rustversion = "1.0.3"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
