[package]
name = "domichain-local-cluster"
description = "Blockchain, Rebuilt for Scale"
documentation = "https://docs.rs/domichain-local-cluster"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
crossbeam-channel = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
domichain-client = { workspace = true }
domichain-config-program = { workspace = true }
domichain-core = { workspace = true }
domichain-entry = { workspace = true }
domichain-gossip = { workspace = true }
domichain-ledger = { workspace = true }
domichain-pubsub-client = { workspace = true }
domichain-rpc-client = { workspace = true }
domichain-rpc-client-api = { workspace = true }
domichain-runtime = { workspace = true }
domichain-sdk = { workspace = true }
domichain-stake-program = { workspace = true }
domichain-streamer = { workspace = true }
domichain-thin-client = { workspace = true }
domichain-tpu-client = { workspace = true }
domichain-vote-program = { workspace = true }
tempfile = { workspace = true }
trees = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
fs_extra = { workspace = true }
gag = { workspace = true }
serial_test = { workspace = true }
domichain-download-utils = { workspace = true }
domichain-logger = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
