[package]
authors = ["Domichain Maintainers <maintainers@domichain.foundation>"]
edition = "2021"
name = "domichain-local-cluster"
description = "Blockchain, Rebuilt for Scale"
version = "1.11.1"
repository = "https://Domino-Blockchain/domichain"
license = "Apache-2.0"
homepage = "https://domichain.com/"
documentation = "https://docs.rs/domichain-local-cluster"

[dependencies]
crossbeam-channel = "0.5"
fs_extra = "1.2.0"
itertools = "0.10.3"
log = "0.4.17"
rand = "0.7.0"
rayon = "1.5.3"
domichain-client = { path = "../client", version = "=1.11.1" }
domichain-config-program = { path = "../programs/config", version = "=1.11.1" }
domichain-core = { path = "../core", version = "=1.11.1" }
domichain-entry = { path = "../entry", version = "=1.11.1" }
domichain-gossip = { path = "../gossip", version = "=1.11.1" }
domichain-ledger = { path = "../ledger", version = "=1.11.1" }
domichain-runtime = { path = "../runtime", version = "=1.11.1" }
domichain-sdk = { path = "../sdk", version = "=1.11.1" }
domichain-stake-program = { path = "../programs/stake", version = "=1.11.1" }
domichain-streamer = { path = "../streamer", version = "=1.11.1" }
domichain-vote-program = { path = "../programs/vote", version = "=1.11.1" }
tempfile = "3.3.0"

[dev-dependencies]
assert_matches = "1.5.0"
gag = "1.0.0"
serial_test = "0.6.0"
domichain-download-utils = { path = "../download-utils", version = "=1.11.1" }
domichain-logger = { path = "../logger", version = "=1.11.1" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
