[package]
name = "domichain-sbf-rust-simulation"
description = "Domichain SBF Program Simulation Differences"
documentation = "https://docs.rs/domichain-sbf-rust-simulation"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[features]
test-bpf = []

[dependencies]
domichain-program = { workspace = true }

[dev-dependencies]
domichain-logger = { workspace = true }
domichain-program-test = { workspace = true }
domichain-sdk = { workspace = true }
domichain-validator = { workspace = true }

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
