[package]
name = "domichain-bpf-loader-program"
version = "1.11.1"
description = "Domichain BPF loader"
authors = ["Domichain Maintainers <maintainers@domichain.foundation>"]
repository = "https://github.com/domichain-labs/domichain"
license = "Apache-2.0"
homepage = "https://domichain.com/"
documentation = "https://docs.rs/domichain-bpf-loader-program"
edition = "2021"

[dependencies]
bincode = "1.3.3"
byteorder = "1.4.3"
libsecp256k1 = "0.6.0"
log = "0.4.17"
domichain-measure = { path = "../../measure", version = "=1.11.1" }
domichain-metrics = { path = "../../metrics", version = "=1.11.1" }
domichain-program-runtime = { path = "../../program-runtime", version = "=1.11.1" }
domichain-sdk = { path = "../../sdk", version = "=1.11.1" }
domichain-zk-token-sdk = { path = "../../zk-token-sdk", version = "=1.11.1" }
solana_rbpf = "=0.2.31"
thiserror = "1.0"

[dev-dependencies]
rand = "0.7.3"
domichain-runtime = { path = "../../runtime", version = "=1.11.1" }

[lib]
crate-type = ["lib"]
name = "domichain_bpf_loader_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
