[package]
name = "domichain-version"
version = "1.11.1"
description = "Domichain Version"
authors = ["Domichain Maintainers <maintainers@domichain.foundation>"]
repository = "https://github.com/domichain-labs/domichain"
license = "Apache-2.0"
homepage = "https://domichain.com/"
documentation = "https://docs.rs/domichain-version"
edition = "2021"

[dependencies]
log = "0.4.17"
semver = "1.0.9"
serde = "1.0.137"
serde_derive = "1.0.103"
domichain-frozen-abi = { path = "../frozen-abi", version = "=1.11.1" }
domichain-frozen-abi-macro = { path = "../frozen-abi/macro", version = "=1.11.1" }
domichain-sdk = { path = "../sdk", version = "=1.11.1" }

[lib]
name = "domichain_version"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
rustc_version = "0.4"
