[package]
name = "domichain-stake-program"
version = "1.11.1"
description = "Domichain Stake program"
authors = ["Domichain Maintainers <maintainers@domichain.foundation>"]
repository = "https://github.com/domichain-labs/domichain"
license = "Apache-2.0"
homepage = "https://domichain.com/"
documentation = "https://docs.rs/domichain-stake-program"
edition = "2021"

[dependencies]
bincode = "1.3.3"
log = "0.4.17"
num-derive = "0.3"
num-traits = "0.2"
serde = "1.0.137"
serde_derive = "1.0.103"
domichain-config-program = { path = "../config", version = "=1.11.1" }
domichain-frozen-abi = { path = "../../frozen-abi", version = "=1.11.1" }
domichain-frozen-abi-macro = { path = "../../frozen-abi/macro", version = "=1.11.1" }
domichain-metrics = { path = "../../metrics", version = "=1.11.1" }
domichain-program-runtime = { path = "../../program-runtime", version = "=1.11.1" }
domichain-sdk = { path = "../../sdk", version = "=1.11.1" }
domichain-vote-program = { path = "../vote", version = "=1.11.1" }
thiserror = "1.0"

[dev-dependencies]
assert_matches = "1.5.0"
proptest = "1.0"
domichain-logger = { path = "../../logger", version = "=1.11.1" }

[build-dependencies]
rustc_version = "0.4"

[lib]
crate-type = ["lib"]
name = "domichain_stake_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
