[package]
name = "domichain-stake-program"
description = "Domichain Stake program"
documentation = "https://docs.rs/domichain-stake-program"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true }
log = { workspace = true }
domichain-config-program = { workspace = true }
domichain-program-runtime = { workspace = true }
domichain-sdk = { workspace = true }
domichain-vote-program = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
proptest = { workspace = true }
domichain-logger = { workspace = true }
test-case = { workspace = true }

[build-dependencies]
rustc_version = { workspace = true }

[lib]
crate-type = ["lib"]
name = "domichain_stake_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
