[package]
name = "domichain-rpc"
description = "Domichain RPC"
documentation = "https://docs.rs/domichain-rpc"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
base64 = { workspace = true }
bincode = { workspace = true }
bs58 = { workspace = true }
crossbeam-channel = { workspace = true }
dashmap = { workspace = true }
itertools = { workspace = true }
jsonrpc-core = { workspace = true }
jsonrpc-core-client = { workspace = true }
jsonrpc-derive = { workspace = true }
jsonrpc-http-server = { workspace = true }
jsonrpc-pubsub = { workspace = true }
libc = { workspace = true }
log = { workspace = true }
rayon = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
soketto = { workspace = true }
domichain-account-decoder = { workspace = true }
domichain-client = { workspace = true }
domichain-entry = { workspace = true }
domichain-faucet = { workspace = true }
domichain-gossip = { workspace = true }
domichain-ledger = { workspace = true }
domichain-measure = { workspace = true }
domichain-metrics = { workspace = true }
domichain-perf = { workspace = true }
domichain-poh = { workspace = true }
domichain-rayon-threadlimit = { workspace = true }
domichain-rpc-client-api = { workspace = true }
domichain-runtime = { workspace = true }
domichain-sdk = { workspace = true }
domichain-send-transaction-service = { workspace = true }
domichain-stake-program = { workspace = true }
domichain-storage-bigtable = { workspace = true }
domichain-streamer = { workspace = true }
domichain-tpu-client = { workspace = true }
domichain-transaction-status = { workspace = true }
domichain-version = { workspace = true }
domichain-vote-program = { workspace = true }
spl-token = { workspace = true, features = ["no-entrypoint"] }
spl-token-2022 = { workspace = true, features = ["no-entrypoint"] }
stream-cancel = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true, features = ["codec", "compat"] }

[dev-dependencies]
serial_test = { workspace = true }
domichain-address-lookup-table-program = { workspace = true }
domichain-net-utils = { workspace = true }
domichain-stake-program = { workspace = true }
symlink = { workspace = true }

[lib]
crate-type = ["lib"]
name = "domichain_rpc"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
