[package]
name = "domichain-transaction-dos"
publish = false
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true }
clap = { workspace = true }
log = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
domichain-clap-utils = { workspace = true }
domichain-cli = { workspace = true }
domichain-client = { workspace = true }
domichain-core = { workspace = true }
domichain-faucet = { workspace = true }
domichain-gossip = { workspace = true }
domichain-logger = { workspace = true }
domichain-measure = { workspace = true }
domichain-net-utils = { workspace = true }
domichain-rpc-client = { workspace = true }
domichain-runtime = { workspace = true }
domichain-sdk = { workspace = true }
domichain-streamer = { workspace = true }
domichain-transaction-status = { workspace = true }
domichain-version = { workspace = true }

[dev-dependencies]
domichain-local-cluster = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
