[package]
name = "domichain-validator"
description = "Blockchain, Rebuilt for Scale"
documentation = "https://docs.rs/domichain-validator"
default-run = "domichain-validator"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
chrono = { workspace = true, features = ["default", "serde"] }
clap = { workspace = true }
console = { workspace = true }
core_affinity = { workspace = true }
crossbeam-channel = { workspace = true }
fd-lock = { workspace = true }
indicatif = { workspace = true }
itertools = { workspace = true }
jsonrpc-core = { workspace = true }
jsonrpc-core-client = { workspace = true, features = ["ipc"] }
jsonrpc-derive = { workspace = true }
jsonrpc-ipc-server = { workspace = true }
jsonrpc-server-utils = { workspace = true }
lazy_static = { workspace = true }
libloading = { workspace = true }
log = { workspace = true }
num_cpus = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
domichain-clap-utils = { workspace = true }
domichain-cli-config = { workspace = true }
domichain-core = { workspace = true }
domichain-download-utils = { workspace = true }
domichain-entry = { workspace = true }
domichain-faucet = { workspace = true }
domichain-genesis-utils = { workspace = true }
domichain-geyser-plugin-interface = { workspace = true }
domichain-geyser-plugin-manager = { workspace = true }
domichain-gossip = { workspace = true }
domichain-ledger = { workspace = true }
domichain-logger = { workspace = true }
domichain-metrics = { workspace = true }
domichain-net-utils = { workspace = true }
domichain-perf = { workspace = true }
domichain-poh = { workspace = true }
domichain-rpc = { workspace = true }
domichain-rpc-client = { workspace = true }
domichain-rpc-client-api = { workspace = true }
domichain-runtime = { workspace = true }
domichain-sdk = { workspace = true }
domichain-send-transaction-service = { workspace = true }
domichain-storage-bigtable = { workspace = true }
domichain-streamer = { workspace = true }
domichain-test-validator = { workspace = true }
domichain-tpu-client = { workspace = true }
domichain-version = { workspace = true }
domichain-vote-program = { workspace = true }
symlink = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
domichain-account-decoder = { workspace = true }
spl-token-2022 = { workspace = true, features = ["no-entrypoint"] }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = { workspace = true }

[target."cfg(unix)".dependencies]
libc = { workspace = true }
signal-hook = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[profile.release]
opt-level = 2
debug = true
incremental = true
codegen-units = 256
