[package]
authors = ["Domichain Maintainers <maintainers@domichain.foundation>"]
edition = "2021"
name = "domichain-validator"
description = "Blockchain, Rebuilt for Scale"
version = "1.11.1"
repository = "https://github.com/domichain-labs/domichain"
license = "Apache-2.0"
homepage = "https://domichain.com/"
documentation = "https://docs.rs/domichain-validator"
default-run = "domichain-validator"

[dependencies]
chrono = { version = "0.4.11", features = ["serde"] }
clap = "2.33.1"
console = "0.15.0"
core_affinity = "0.5.10"
crossbeam-channel = "0.5"
fd-lock = "3.0.5"
indicatif = "0.16.2"
jsonrpc-core = "18.0.0"
jsonrpc-core-client = { version = "18.0.0", features = ["ipc"] }
jsonrpc-derive = "18.0.0"
jsonrpc-ipc-server = "18.0.0"
jsonrpc-server-utils = "18.0.0"
log = "0.4.17"
num_cpus = "1.13.1"
rand = "0.7.0"
serde = "1.0.137"
serde_json = "1.0.81"
domichain-clap-utils = { path = "../clap-utils", version = "=1.11.1" }
domichain-cli-config = { path = "../cli-config", version = "=1.11.1" }
domichain-client = { path = "../client", version = "=1.11.1" }
domichain-core = { path = "../core", version = "=1.11.1" }
domichain-download-utils = { path = "../download-utils", version = "=1.11.1" }
domichain-entry = { path = "../entry", version = "=1.11.1" }
domichain-faucet = { path = "../faucet", version = "=1.11.1" }
domichain-genesis-utils = { path = "../genesis-utils", version = "=1.11.1" }
domichain-gossip = { path = "../gossip", version = "=1.11.1" }
domichain-ledger = { path = "../ledger", version = "=1.11.1" }
domichain-logger = { path = "../logger", version = "=1.11.1" }
domichain-metrics = { path = "../metrics", version = "=1.11.1" }
domichain-net-utils = { path = "../net-utils", version = "=1.11.1" }
domichain-perf = { path = "../perf", version = "=1.11.1" }
domichain-poh = { path = "../poh", version = "=1.11.1" }
domichain-rpc = { path = "../rpc", version = "=1.11.1" }
domichain-runtime = { path = "../runtime", version = "=1.11.1" }
domichain-sdk = { path = "../sdk", version = "=1.11.1" }
domichain-send-transaction-service = { path = "../send-transaction-service", version = "=1.11.1" }
domichain-storage-bigtable = { path = "../storage-bigtable", version = "=1.11.1" }
domichain-streamer = { path = "../streamer", version = "=1.11.1" }
domichain-test-validator = { path = "../test-validator", version = "=1.11.1" }
domichain-version = { path = "../version", version = "=1.11.1" }
domichain-vote-program = { path = "../programs/vote", version = "=1.11.1" }
symlink = "0.1.0"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = { package = "tikv-jemallocator", version = "0.4.1", features = ["unprefixed_malloc_on_supported_platforms"] }

[target."cfg(unix)".dependencies]
libc = "0.2.126"
signal-hook = "0.3.14"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
