[package]
name = "domichain-runtime"
version = "1.11.1"
description = "Domichain runtime"
authors = ["Domichain Maintainers <maintainers@domichain.foundation>"]
repository = "https://Domino-Blockchain/domichain"
license = "Apache-2.0"
homepage = "https://domichain.com/"
documentation = "https://docs.rs/domichain-runtime"
edition = "2021"

[dependencies]
arrayref = "0.3.6"
bincode = "1.3.3"
blake3 = "1.3.1"
bv = { version = "0.11.1", features = ["serde"] }
bytemuck = "1.9.1"
byteorder = "1.4.3"
bzip2 = "0.4.3"
crossbeam-channel = "0.5"
dashmap = { version = "4.0.2", features = ["rayon", "raw-api"] }
dir-diff = "0.3.2"
flate2 = "1.0.24"
fnv = "1.0.7"
im = { version = "15.1.0", features = ["rayon", "serde"] }
index_list = "0.2.7"
itertools = "0.10.3"
lazy_static = "1.4.0"
log = "0.4.17"
memmap2 = "0.5.3"
num-derive = { version = "0.3" }
num-traits = { version = "0.2" }
num_cpus = "1.13.1"
ouroboros = "0.15.0"
rand = "0.7.0"
rayon = "1.5.3"
regex = "1.5.6"
serde = { version = "1.0.137", features = ["rc"] }
serde_derive = "1.0.103"
domichain-address-lookup-table-program = { path = "../programs/address-lookup-table", version = "=1.11.1" }
domichain-bucket-map = { path = "../bucket_map", version = "=1.11.1" }
domichain-compute-budget-program = { path = "../programs/compute-budget", version = "=1.11.1" }
domichain-config-program = { path = "../programs/config", version = "=1.11.1" }
domichain-frozen-abi = { path = "../frozen-abi", version = "=1.11.1" }
domichain-frozen-abi-macro = { path = "../frozen-abi/macro", version = "=1.11.1" }
domichain-measure = { path = "../measure", version = "=1.11.1" }
domichain-metrics = { path = "../metrics", version = "=1.11.1" }
domichain-program-runtime = { path = "../program-runtime", version = "=1.11.1" }
domichain-rayon-threadlimit = { path = "../rayon-threadlimit", version = "=1.11.1" }
domichain-sdk = { path = "../sdk", version = "=1.11.1" }
domichain-stake-program = { path = "../programs/stake", version = "=1.11.1" }
domichain-vote-program = { path = "../programs/vote", version = "=1.11.1" }
domichain-zk-token-proof-program = { path = "../programs/zk-token-proof", version = "=1.11.1" }
domichain-zk-token-sdk = { path = "../zk-token-sdk", version = "=1.11.1" }
symlink = "0.1.0"
tar = "0.4.38"
tempfile = "3.3.0"
thiserror = "1.0"
zstd = "0.11.2"
lz4 = "1.23.3"
strum_macros = "0.24"
strum = { version = "0.24", features = ["derive"] }

[lib]
crate-type = ["lib"]
name = "domichain_runtime"

[dev-dependencies]
assert_matches = "1.5.0"
ed25519-dalek = "=1.0.1"
libsecp256k1 = "0.6.0"
rand_chacha = "0.2.2"
domichain-logger = { path = "../logger", version = "=1.11.1" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
rustc_version = "0.4"
