[package]
name = "domichain-merkle-tree"
version = "1.11.1"
description = "Domichain Merkle Tree"
authors = ["Domichain Maintainers <maintainers@domichain.foundation>"]
repository = "https://github.com/domichain-labs/domichain"
license = "Apache-2.0"
homepage = "https://domichain.com/"
documentation = "https://docs.rs/domichain-merkle-tree"
edition = "2021"

[dependencies]
fast-math = "0.1"
domichain-program = { path = "../sdk/program", version = "=1.11.1" }

# This can go once the BPF toolchain target Rust 1.42.0+
[target.bpfel-unknown-unknown.dependencies]
matches = "0.1.9"

[dev-dependencies]
hex = "0.4.3"

[lib]
crate-type = ["lib"]
name = "domichain_merkle_tree"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
