[package]
name = "domichain-merkle-tree"
description = "Domichain Merkle Tree"
documentation = "https://docs.rs/domichain-merkle-tree"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
fast-math = { workspace = true }
domichain-program = { workspace = true }

# This can go once the SBF toolchain target Rust 1.42.0+
[target.bpfel-unknown-unknown.dependencies]
matches = { workspace = true }

[dev-dependencies]
hex = { workspace = true }

[lib]
crate-type = ["lib"]
name = "domichain_merkle_tree"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
