[package]
name = "domichain-address-lookup-table-program"
description = "Domichain address lookup table program"
documentation = "https://docs.rs/domichain-address-loookup-table-program"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true }
bytemuck = { workspace = true }
log = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
serde = { workspace = true, features = ["derive"] }
domichain-frozen-abi = { workspace = true }
domichain-frozen-abi-macro = { workspace = true }
domichain-program = { workspace = true }
thiserror = { workspace = true }

[target.'cfg(not(target_os = "wasi"))'.dependencies]
domichain-program-runtime = { workspace = true }
domichain-sdk = { workspace = true }

[build-dependencies]
rustc_version = { workspace = true }

[lib]
crate-type = ["lib"]
name = "domichain_address_lookup_table_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
