[package]
authors = ["Domichain Maintainers <maintainers@domichain.com>"]
edition = "2021"
name = "domichain-log-analyzer"
description = "The domichain cluster network analysis tool"
version = "1.11.1"
repository = "https://github.com/domichain-labs/domichain"
license = "Apache-2.0"
homepage = "https://domichain.com/"
publish = false

[dependencies]
byte-unit = "4.0.14"
clap = { version = "3.1.5", features = ["cargo"] }
serde = "1.0.137"
serde_json = "1.0.81"
domichain-logger = { path = "../logger", version = "=1.11.1" }
domichain-version = { path = "../version", version = "=1.11.1" }

[[bin]]
name = "domichain-log-analyzer"
path = "src/main.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
