[package]
name = "libvrf"
version = "1.16.1"
edition = "2021"

[dependencies]
libvrf-sys = { path = "../libvrf-sys", version = "=0.1.0" }
domichain-sdk = { path = "../sdk", version = "=1.16.1" }
log = "0.4.17"