[package]
name = "domichain-compute-budget-program"
description = "Domichain Compute Budget program"
documentation = "https://docs.rs/domichain-compute-budget-program"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
domichain-program-runtime = { workspace = true }
domichain-sdk = { workspace = true }

[lib]
crate-type = ["lib"]
name = "domichain_compute_budget_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
