[package]
name = "domichain-compute-budget-program"
description = "Domichain Compute Budget program"
version = "1.11.1"
homepage = "https://domichain.com/"
documentation = "https://docs.rs/domichain-compute-budget-program"
repository = "https://Domino-Blockchain/domichain"
authors = ["Domichain Maintainers <maintainers@domichain.foundation>"]
license = "Apache-2.0"
edition = "2021"

[dependencies]
domichain-program-runtime = { path = "../../program-runtime", version = "=1.11.1" }
domichain-sdk = { path = "../../sdk", version = "=1.11.1" }

[lib]
crate-type = ["lib"]
name = "domichain_compute_budget_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
