[package]
name = "domichain-bpf-rust-sha"
version = "1.11.1"
description = "Domichain BPF test program written in Rust"
authors = ["Domichain Maintainers <maintainers@domichain.foundation>"]
repository = "https://github.com/domichain-labs/domichain"
license = "Apache-2.0"
homepage = "https://domichain.com/"
documentation = "https://docs.rs/domichain-bpf-rust-sha"
edition = "2021"

[dependencies]
blake3 = "1.0.0"
domichain-program = { path = "../../../../sdk/program", version = "=1.11.1" }

[lib]
crate-type = ["cdylib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
