[package]
name = "domichain-program-runtime"
description = "Domichain program runtime"
documentation = "https://docs.rs/domichain-program-runtime"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
base64 = { workspace = true }
bincode = { workspace = true }
eager = { workspace = true }
enum-iterator = { workspace = true }
itertools = { workspace = true }
libc = { workspace = true }
log = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
percentage = { workspace = true }
rand = { workspace = true }
serde = { version = "1.0.163", features = ["derive", "rc"] }
domichain-frozen-abi = { workspace = true }
domichain-frozen-abi-macro = { workspace = true }
domichain-measure = { workspace = true }
domichain-metrics = { workspace = true }
domichain-sdk = { workspace = true }
solana_rbpf = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
domichain-logger = { workspace = true }

[lib]
crate-type = ["lib"]
name = "domichain_program_runtime"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
rustc_version = { workspace = true }
