[package]
name = "domichain-program-runtime"
version = "1.11.1"
description = "Domichain program runtime"
authors = ["Domichain Maintainers <maintainers@domichain.foundation>"]
repository = "https://Domino-Blockchain/domichain"
license = "Apache-2.0"
homepage = "https://domichain.com/"
documentation = "https://docs.rs/domichain-program-runtime"
edition = "2021"

[dependencies]
base64 = "0.13"
bincode = "1.3.3"
itertools =  "0.10.1"
libc = "0.2.101"
libloading = "0.7.0"
log = "0.4.14"
num-derive = { version = "0.3" }
num-traits = { version = "0.2" }
serde = { version = "1.0.129", features = ["derive", "rc"] }
domichain-frozen-abi = { path = "../frozen-abi", version = "=1.11.1" }
domichain-frozen-abi-macro = { path = "../frozen-abi/macro", version = "=1.11.1" }
domichain-measure = { path = "../measure", version = "=1.11.1" }
domichain-sdk = { path = "../sdk", version = "=1.11.1" }
thiserror = "1.0"
enum-iterator = "0.8.1"

[dev-dependencies]
domichain-logger = { path = "../logger", version = "=1.11.1" }

[lib]
crate-type = ["lib"]
name = "domichain_program_runtime"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
rustc_version = "0.4"
