[package]
name = "domichain-udp-client"
description = "Domichain UDP Client"
documentation = "https://docs.rs/domichain-udp-client"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
async-trait = { workspace = true }
domichain-connection-cache = { workspace = true }
domichain-net-utils = { workspace = true }
domichain-sdk = { workspace = true }
domichain-streamer = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
