[package]
name = "domichain-notifier"
version = "1.11.1"
description = "Domichain Notifier"
authors = ["Domichain Maintainers <maintainers@domichain.foundation>"]
repository = "https://github.com/domichain-labs/domichain"
license = "Apache-2.0"
homepage = "https://domichain.com/"
documentation = "https://docs.rs/domichain-notifier"
edition = "2021"

[dependencies]
log = "0.4.17"
reqwest = { version = "0.11.10", default-features = false, features = ["blocking", "rustls-tls", "json"] }
serde_json = "1.0"

[lib]
name = "domichain_notifier"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
