[package]
name = "domichain-stake-accounts"
description = "Blockchain, Rebuilt for Scale"
documentation = "https://docs.rs/domichain-stake-accounts"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
clap = { workspace = true }
domichain-clap-utils = { workspace = true }
domichain-cli-config = { workspace = true }
domichain-remote-wallet = { workspace = true, features = ["default"] }
domichain-rpc-client = { workspace = true, features = ["default"] }
domichain-rpc-client-api = { workspace = true }
domichain-sdk = { workspace = true }
domichain-stake-program = { workspace = true }
domichain-version = { workspace = true }

[dev-dependencies]
domichain-runtime = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
