[package]
name = "domichain-zk-token-proof-program"
description = "Domichain Zk Token Proof Program"
authors = ["Domichain Maintainers <maintainers@domichain.foundation>"]
repository = "https://github.com/domichain-labs/domichain"
version = "1.11.1"
license = "Apache-2.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.9.1", features = ["derive"] }
getrandom = { version = "0.1", features = ["dummy"] }
num-derive = "0.3"
num-traits = "0.2"
domichain-program-runtime = { path = "../../program-runtime", version = "=1.11.1" }
domichain-sdk = { path = "../../sdk", version = "=1.11.1" }
domichain-zk-token-sdk = { path = "../../zk-token-sdk", version = "=1.11.1" }
