[package]
name = "domichain-tokens"
description = "Blockchain, Rebuilt for Scale"
documentation = "https://docs.rs/domichain-tokens"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
chrono = { workspace = true, features = ["default", "serde"] }
clap = "2.33.0"
console = { workspace = true }
csv = { workspace = true }
ctrlc = { workspace = true, features = ["termination"] }
indexmap = { workspace = true }
indicatif = { workspace = true }
pickledb = { workspace = true, features = ["yaml"] }
serde = { workspace = true, features = ["derive"] }
domichain-account-decoder = { workspace = true }
domichain-clap-utils = { workspace = true }
domichain-cli-config = { workspace = true }
domichain-remote-wallet = { workspace = true, features = ["default"] }
domichain-rpc-client = { workspace = true, features = ["default"] }
domichain-rpc-client-api = { workspace = true }
domichain-sdk = { workspace = true }
domichain-transaction-status = { workspace = true }
domichain-version = { workspace = true }
spl-associated-token-account = { workspace = true }
spl-token = { workspace = true, features = ["no-entrypoint"] }
tempfile = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
bincode = { workspace = true }
domichain-logger = { workspace = true }
domichain-streamer = { workspace = true }
domichain-test-validator = { workspace = true }
