[package]
name = "domichain-zk-token-sdk"
description = "Domichain Zk Token SDK"
documentation = "https://docs.rs/domichain-zk-token-sdk"
version = "1.16.1"
edition = "2021"
# version = { workspace = true }
# authors = { workspace = true }
# repository = { workspace = true }
# homepage = { workspace = true }
# license = { workspace = true }
# edition = { workspace = true }

[dependencies]
base64 = { workspace = true }
bytemuck = { workspace = true, features = ["derive"] }
num-derive = { workspace = true }
num-traits = { workspace = true }
domichain-program = { path = "../sdk/program" }
# domichain-program = { workspace = true }

[dev-dependencies]
tiny-bip39 = { workspace = true }

[target.'cfg(not(target_os = "wasi"))'.dependencies]
aes-gcm-siv = { workspace = true }
arrayref = { workspace = true }
bincode = { workspace = true }
byteorder = { workspace = true }
curve25519-dalek = { workspace = true, features = ["serde"] }
getrandom = { workspace = true, features = ["dummy"] }
itertools = { workspace = true }
lazy_static = { workspace = true }
merlin = { workspace = true }
rand = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sha3 = "0.9"
domichain-sdk = { path = "../sdk" }
# domichain-sdk = { workspace = true }
subtle = { workspace = true }
thiserror = { workspace = true }
zeroize = { workspace = true, features = ["zeroize_derive"] }

[lib]
crate-type = ["cdylib", "rlib"]
