[package]
name = "domichain-poh-bench"
documentation = "https://docs.rs/domichain-poh-bench"
publish = false
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
clap = { version = "3.1.5", features = ["cargo"] }
log = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
domichain-entry = { workspace = true }
domichain-logger = { workspace = true }
domichain-measure = { workspace = true }
domichain-perf = { workspace = true }
domichain-sdk = { workspace = true }
domichain-version = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
