[package]
name = "rbpf-cli"
version = "1.11.1"
description = "CLI to test and analyze eBPF programs"
authors = ["Domichain Maintainers <maintainers@domichain.foundation>"]
repository = "https://github.com/domichain-labs/rbpf"
homepage = "https://domichain.com/"
keywords = ["BPF", "eBPF", "interpreter", "JIT"]
edition = "2021"
publish = false

[dependencies]
clap = { version = "3.1.5", features = ["cargo"] }
serde = "1.0.137"
serde_json = "1.0.81"
domichain-bpf-loader-program = { path = "../programs/bpf_loader", version = "=1.11.1" }
domichain-logger = { path = "../logger", version = "=1.11.1" }
domichain-program-runtime = { path = "../program-runtime", version = "=1.11.1" }
domichain-sdk = { path = "../sdk", version = "=1.11.1" }
solana_rbpf = "=0.2.31"
