[package]
name = "domichain-storage-proto"
version = "1.11.1"
description = "Domichain Storage Protobuf Definitions"
authors = ["Domichain Maintainers <maintainers@domichain.com>"]
repository = "https://Domino-Blockchain/domichain"
license = "Apache-2.0"
homepage = "https://domichain.com/"
documentation = "https://docs.rs/domichain-storage-proto"
edition = "2021"

[dependencies]
bincode = "1.3.3"
bs58 = "0.4.0"
prost = "0.10.4"
serde = "1.0.137"
domichain-account-decoder = { path = "../account-decoder", version = "=1.11.1" }
domichain-sdk = { path = "../sdk", version = "=1.11.1" }
domichain-transaction-status = { path = "../transaction-status", version = "=1.11.1" }

[dev-dependencies]
enum-iterator = "1.2.0"

[lib]
crate-type = ["lib"]
name = "domichain_storage_proto"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
tonic-build = "0.7.2"
