[package]
name = "domichain-logger"
version = "1.11.1"
description = "Domichain Logger"
authors = ["Domichain Maintainers <maintainers@domichain.foundation>"]
repository = "https://github.com/domichain-labs/domichain"
license = "Apache-2.0"
homepage = "https://domichain.com/"
documentation = "https://docs.rs/domichain-logger"
edition = "2021"

[dependencies]
env_logger = "0.9.0"
lazy_static = "1.4.0"
log = "0.4.17"

[lib]
name = "domichain_logger"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
