[package]
name = "domichain-logger"
description = "Domichain Logger"
documentation = "https://docs.rs/domichain-logger"
version = "1.0.0"
edition = "2021"
# version = { workspace = true }
# authors = { workspace = true }
# repository = { workspace = true }
# homepage = { workspace = true }
# license = { workspace = true }
# edition = { workspace = true }

[dependencies]
env_logger = { workspace = true }
lazy_static = { workspace = true }
log = { workspace = true }

[lib]
name = "domichain_logger"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
