[package]
name = "domichain-cargo-test-sbf"
version = "1.11.1"
description = "Execute all unit and integration tests after building with the Domichain SBF SDK"
authors = ["Domichain Maintainers <maintainers@domichain.foundation>"]
repository = "https://github.com/domichain-labs/domichain"
homepage = "https://domichain.com/"
license = "Apache-2.0"
edition = "2021"
publish = false

[dependencies]
cargo_metadata = "0.14.2"
clap = { version = "3.1.5", features = ["cargo"] }

[[bin]]
name = "cargo-test-sbf"
path = "src/main.rs"
