[package]
name = "domichain-rayon-threadlimit"
version = "1.11.1"
description = "domichain-rayon-threadlimit"
homepage = "https://domichain.com/"
documentation = "https://docs.rs/domichain-rayon-threadlimit"
readme = "../README.md"
repository = "https://Domino-Blockchain/domichain"
authors = ["Domichain Maintainers <maintainers@domichain.foundation>"]
license = "Apache-2.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
num_cpus = "1.13.1"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
