[package]
name = "sortition"
version = "0.1.0"
edition = "2021"

[dependencies]
domichain-program = { path = "../sdk/program", version = "=1.11.1" }
statrs = "0.15.0"
num-rational = "0.4.1"
num-bigint = "0.4.3"
num-traits = "0.2.15"

[dev-dependencies]
rand = "0.8.5"