[package]
name = "sortition"
version = "0.1.0"
edition = "2021"

[dependencies]
domichain-program = { path = "../sdk/program", version = "=1.16.1" }
primitive-types = { version = "0.11.1", features = ["fp-conversion"] }
statrs = "0.15.0"

[dev-dependencies]
rand = "0.8.5"
