# This package only exists to avoid circular dependencies during cargo publish:
# domichain-runtime -> domichain-address-program -> domichain-program-test -> domichain-runtime

[package]
name = "domichain-address-lookup-table-program-tests"
publish = false
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
bincode = { workspace = true }
domichain-address-lookup-table-program = { workspace = true }
domichain-program-test = { workspace = true }
domichain-sdk = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
