[package]
name = "domichain-test-validator"
description = "Blockchain, Rebuilt for Scale"
readme = "../README.md"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
base64 = { workspace = true }
bincode = { workspace = true }
crossbeam-channel = { workspace = true }
log = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
domichain-cli-output = { workspace = true }
domichain-client = { workspace = true }
domichain-core = { workspace = true }
domichain-geyser-plugin-manager = { workspace = true }
domichain-gossip = { workspace = true }
domichain-ledger = { workspace = true }
domichain-logger = { workspace = true }
domichain-net-utils = { workspace = true }
domichain-program-runtime = { workspace = true }
domichain-program-test = { workspace = true }
domichain-rpc = { workspace = true }
domichain-rpc-client = { workspace = true }
domichain-runtime = { workspace = true }
domichain-sdk = { workspace = true }
domichain-streamer = { workspace = true }
domichain-tpu-client = { workspace = true }
tokio = { workspace = true, features = ["full"] }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
