[package]
name = "domichain-net-utils"
version = "1.11.1"
description = "Domichain Network Utilities"
authors = ["Domichain Maintainers <maintainers@domichain.foundation>"]
repository = "https://github.com/domichain-labs/domichain"
license = "Apache-2.0"
homepage = "https://domichain.com/"
documentation = "https://docs.rs/domichain-net-utils"
edition = "2021"

[dependencies]
bincode = "1.3.3"
clap = { version = "3.1.5", features = ["cargo"] }
crossbeam-channel = "0.5"
log = "0.4.17"
nix = "0.24.0"
rand = "0.7.0"
serde = "1.0.137"
serde_derive = "1.0.103"
socket2 = "0.4.4"
domichain-logger = { path = "../logger", version = "=1.11.1" }
domichain-sdk = { path = "../sdk", version = "=1.11.1" }
domichain-version = { path = "../version", version = "=1.11.1" }
tokio = { version = "~1.14.1", features = ["full"] }
url = "2.2.2"

[lib]
name = "domichain_net_utils"

[[bin]]
name = "domichain-ip-address"
path = "src/bin/ip_address.rs"

[[bin]]
name = "domichain-ip-address-server"
path = "src/bin/ip_address_server.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
