[package]
name = "domichain-rpc-test"
description = "Domichain RPC Test"
documentation = "https://docs.rs/domichain-rpc-test"
publish = false
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true }
bs58 = { workspace = true }
crossbeam-channel = { workspace = true }
futures-util = { workspace = true }
log = { workspace = true }
reqwest = { workspace = true, features = ["blocking", "brotli", "deflate", "gzip", "rustls-tls", "json"] }
serde = { workspace = true }
serde_json = { workspace = true }
domichain-account-decoder = { workspace = true }
domichain-client = { workspace = true }
domichain-pubsub-client = { workspace = true }
domichain-rpc = { workspace = true }
domichain-rpc-client = { workspace = true }
domichain-rpc-client-api = { workspace = true }
domichain-sdk = { workspace = true }
domichain-streamer = { workspace = true }
domichain-test-validator = { workspace = true }
domichain-tpu-client = { workspace = true }
domichain-transaction-status = { workspace = true }
tokio = { workspace = true, features = ["full"] }

[dev-dependencies]
domichain-logger = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
