[package]
name = "domichain-rpc-test"
version = "1.11.1"
description = "Domichain RPC Test"
authors = ["Domichain Maintainers <maintainers@domichain.foundation>"]
repository = "https://github.com/domichain-labs/domichain"
license = "Apache-2.0"
homepage = "https://domichain.com/"
documentation = "https://docs.rs/domichain-rpc-test"
edition = "2021"
publish = false

[dependencies]
bincode = "1.3.3"
bs58 = "0.4.0"
crossbeam-channel = "0.5"
futures-util = "0.3.21"
log = "0.4.17"
reqwest = { version = "0.11.10", default-features = false, features = ["blocking", "rustls-tls", "json"] }
serde = "1.0.137"
serde_json = "1.0.81"
domichain-account-decoder = { path = "../account-decoder", version = "=1.11.1" }
domichain-client = { path = "../client", version = "=1.11.1" }
domichain-rpc = { path = "../rpc", version = "=1.11.1" }
domichain-sdk = { path = "../sdk", version = "=1.11.1" }
domichain-streamer = { path = "../streamer", version = "=1.11.1" }
domichain-test-validator = { path = "../test-validator", version = "=1.11.1" }
domichain-transaction-status = { path = "../transaction-status", version = "=1.11.1" }
tokio = { version = "~1.14.1", features = ["full"] }

[dev-dependencies]
domichain-logger = { path = "../logger", version = "=1.11.1" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
