[package]
name = "domichain-ledger-tool"
description = "Blockchain, Rebuilt for Scale"
documentation = "https://docs.rs/domichain-ledger-tool"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bs58 = { workspace = true }
chrono = { workspace = true, features = ["default"] }
clap = { workspace = true }
crossbeam-channel = { workspace = true }
csv = { workspace = true }
dashmap = { workspace = true }
futures = { workspace = true }
histogram = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
num_cpus = { workspace = true }
regex = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
domichain-account-decoder = { workspace = true }
domichain-bpf-loader-program = { workspace = true }
domichain-clap-utils = { workspace = true }
domichain-cli-output = { workspace = true }
domichain-core = { workspace = true }
domichain-entry = { workspace = true }
domichain-geyser-plugin-manager = { workspace = true }
domichain-gossip = { workspace = true }
domichain-ledger = { workspace = true }
domichain-logger = { workspace = true }
domichain-measure = { workspace = true }
domichain-program-runtime = { workspace = true }
domichain-rpc = { workspace = true }
domichain-runtime = { workspace = true }
domichain-sdk = { workspace = true }
domichain-stake-program = { workspace = true }
domichain-storage-bigtable = { workspace = true }
domichain-streamer = { workspace = true }
domichain-transaction-status = { workspace = true }
domichain-version = { workspace = true }
domichain-vote-program = { workspace = true }
domichain_rbpf = { workspace = true, features = ["debugger"] }
tokio = { workspace = true, features = ["full"] }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = { workspace = true }

[dev-dependencies]
assert_cmd = { workspace = true }
bytecount = { workspace = true }

[target."cfg(unix)".dependencies]
signal-hook = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
