[package]
authors = ["Domichain Maintainers <maintainers@domichain.foundation>"]
edition = "2021"
name = "domichain-ledger-tool"
description = "Blockchain, Rebuilt for Scale"
version = "1.11.1"
repository = "https://Domino-Blockchain/domichain"
license = "Apache-2.0"
homepage = "https://domichain.com/"
documentation = "https://docs.rs/domichain-ledger-tool"

[dependencies]
bs58 = "0.4.0"
clap = "2.33.1"
chrono = "0.4.11"
crossbeam-channel = "0.5"
csv = "1.1.6"
dashmap = "4.0.2"
histogram = "0.6.9"
itertools = "0.10.3"
log = { version = "0.4.17" }
regex = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.81"
domichain-clap-utils = { path = "../clap-utils", version = "=1.11.1" }
domichain-cli-output = { path = "../cli-output", version = "=1.11.1" }
domichain-core = { path = "../core", version = "=1.11.1" }
domichain-entry = { path = "../entry", version = "=1.11.1" }
domichain-ledger = { path = "../ledger", version = "=1.11.1" }
domichain-logger = { path = "../logger", version = "=1.11.1" }
domichain-measure = { path = "../measure", version = "=1.11.1" }
domichain-runtime = { path = "../runtime", version = "=1.11.1" }
domichain-sdk = { path = "../sdk", version = "=1.11.1" }
domichain-stake-program = { path = "../programs/stake", version = "=1.11.1" }
domichain-storage-bigtable = { path = "../storage-bigtable", version = "=1.11.1" }
domichain-transaction-status = { path = "../transaction-status", version = "=1.11.1" }
domichain-version = { path = "../version", version = "=1.11.1" }
domichain-vote-program = { path = "../programs/vote", version = "=1.11.1" }
tokio = { version = "~1.14.1", features = ["full"] }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = { package = "tikv-jemallocator", version = "0.4.1", features = ["unprefixed_malloc_on_supported_platforms"] }

[dev-dependencies]
assert_cmd = "2.0"
bytecount = "0.6.2"

[target."cfg(unix)".dependencies]
signal-hook = "0.3.14"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
