[package]
name = "domichain-storage-bigtable"
version = "1.11.1"
description = "Domichain Storage BigTable"
authors = ["Domichain Maintainers <maintainers@domichain.com>"]
repository = "https://Domino-Blockchain/domichain"
license = "Apache-2.0"
homepage = "https://domichain.com/"
documentation = "https://docs.rs/domichain-storage-bigtable"
edition = "2021"

[dependencies]
backoff = { version = "0.4.0", features = ["tokio"] }
bincode = "1.3.3"
bzip2 = "0.4.3"
enum-iterator = "1.2.0"
flate2 = "1.0.24"
futures = "0.3.21"
goauth = "0.13.0"
log = "0.4.17"
prost = "0.10.4"
prost-types = "0.10.0"
serde = "1.0.137"
serde_derive = "1.0.103"
smpl_jwt = "0.7.1"
domichain-metrics = { path = "../metrics", version = "=1.11.1" }
domichain-sdk = { path = "../sdk", version = "=1.11.1" }
domichain-storage-proto = { path = "../storage-proto", version = "=1.11.1" }
domichain-transaction-status = { path = "../transaction-status", version = "=1.11.1" }
thiserror = "1.0"
tokio = "~1.14.1"
tonic = { version = "0.7.2", features = ["tls", "transport"] }
zstd = "0.11.2"

# openssl is a dependency of the goauth and smpl_jwt crates, but explicitly
# declare it here as well to activate the "vendored" feature that builds OpenSSL
# statically...
[target."cfg(not(windows))".dependencies]
openssl = { version = "0.10", features = ["vendored"] }
# ...except on Windows to avoid having to deal with getting CI past a build-time
# Perl dependency
[target."cfg(windows)".dependencies]
openssl = { version = "0.10", features = [] }

[lib]
crate-type = ["lib"]
name = "domichain_storage_bigtable"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
