[package]
description = "Domichain Program Test Framework"
name = "domichain-program-test"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
assert_matches = { workspace = true }
async-trait = { workspace = true }
base64 = { workspace = true }
bincode = { workspace = true }
chrono-humanize = { workspace = true }
crossbeam-channel = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
domichain-banks-client = { workspace = true }
domichain-banks-interface = { workspace = true }
domichain-banks-server = { workspace = true }
domichain-bpf-loader-program = { workspace = true }
domichain-logger = { workspace = true }
domichain-program-runtime = { workspace = true }
domichain-runtime = { workspace = true }
domichain-sdk = { workspace = true }
domichain-vote-program = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }

[dev-dependencies]
domichain-stake-program = { workspace = true }
