[package]
authors = ["Domichain Maintainers <maintainers@domichain.foundation>"]
description = "Domichain Program Test Framework"
edition = "2021"
license = "Apache-2.0"
name = "domichain-program-test"
repository = "https://github.com/domichain-labs/domichain"
version = "1.11.1"

[dependencies]
assert_matches = "1.5.0"
async-trait = "0.1.53"
base64 = "0.13.0"
bincode = "1.3.3"
chrono-humanize = "0.2.1"
log = "0.4.17"
serde = "1.0.137"
domichain-banks-client = { path = "../banks-client", version = "=1.11.1" }
domichain-banks-server = { path = "../banks-server", version = "=1.11.1" }
domichain-bpf-loader-program = { path = "../programs/bpf_loader", version = "=1.11.1" }
domichain-logger = { path = "../logger", version = "=1.11.1" }
domichain-program-runtime = { path = "../program-runtime", version = "=1.11.1" }
domichain-runtime = { path = "../runtime", version = "=1.11.1" }
domichain-sdk = { path = "../sdk", version = "=1.11.1" }
domichain-vote-program = { path = "../programs/vote", version = "=1.11.1" }
thiserror = "1.0"
tokio = { version = "~1.14.1", features = ["full"] }
