[package]
name = "domichain-wasm-loader-program"
description = "Domichain WASM loader"
documentation = "https://docs.rs/domichain-wasm-loader-program"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
itertools = "0.11.0"
bincode = { workspace = true }
borsh = { workspace = true }
bytemuck = { workspace = true, features = ["derive"] }
byteorder = { workspace = true }
hex = { workspace = true }
libsecp256k1 = { workspace = true }
log = { workspace = true }
rand = { workspace = true }
domichain-measure = { workspace = true }
domichain-program-runtime = { workspace = true }
domichain-sdk = { workspace = true }
domichain-zk-token-sdk = { workspace = true }
sha2 = { workspace = true }
solana_rbpf = { workspace = true }
thiserror = { workspace = true }
wasmi = { workspace = true }
wasmi_wasi = { workspace = true }

[dev-dependencies]
memoffset = { workspace = true }

[lib]
crate-type = ["lib"]
name = "domichain_wasm_loader_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
