[package]
name = "domichain-upload-perf"
version = "1.11.1"
description = "Metrics Upload Utility"
authors = ["Domichain Maintainers <maintainers@domichain.foundation>"]
repository = "https://Domino-Blockchain/domichain"
license = "Apache-2.0"
edition = "2021"
homepage = "https://domichain.com/"
publish = false

[dependencies]
serde_json = "1.0.81"
domichain-metrics = { path = "../metrics", version = "=1.11.1" }

[[bin]]
name = "domichain-upload-perf"
path = "src/upload-perf.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
