[package]
name = "domichain-bpf-rust-simulation"
version = "1.11.1"
description = "Domichain BPF Program Simulation Differences"
authors = ["Domichain Maintainers <maintainers@domichain.foundation>"]
repository = "https://github.com/domichain-labs/domichain"
license = "Apache-2.0"
homepage = "https://domichain.com/"
documentation = "https://docs.rs/domichain-bpf-rust-simulation"
edition = "2021"

[features]
test-bpf = []

[dependencies]
domichain-program = { path = "../../../../sdk/program", version = "=1.11.1" }

[dev-dependencies]
domichain-logger = { path = "../../../../logger", version = "=1.11.1" }
domichain-program-test = { path = "../../../../program-test", version = "=1.11.1" }
domichain-sdk = { path = "../../../../sdk", version = "=1.11.1" }
domichain-validator = { path = "../../../../validator", version = "=1.11.1" }

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
