[package]
name = "domichain-measure"
description = "Blockchain, Rebuilt for Scale"
version = "1.11.1"
homepage = "https://domichain.com/"
documentation = "https://docs.rs/domichain-measure"
readme = "../README.md"
repository = "https://github.com/domichain-labs/domichain"
authors = ["Domichain Maintainers <maintainers@domichain.foundation>"]
license = "Apache-2.0"
edition = "2021"

[dependencies]
log = "0.4.17"
domichain-sdk = { path = "../sdk", version = "=1.11.1" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
