[package]
name = "domichain-rpc-client-nonce-utils"
description = "Domichain RPC Client Nonce Utilities"
documentation = "https://docs.rs/domichain-nonce-client"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
clap = "2.33.0"
domichain-clap-utils = { workspace = true }
domichain-rpc-client = { workspace = true }
domichain-sdk = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
futures = { workspace = true }
serde_json = { workspace = true }
domichain-account-decoder = { workspace = true }
domichain-rpc-client-api = { workspace = true }
tokio = { workspace = true, features = ["full"] }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
