[package]
name = "domichain-bpf-rust-dep-crate"
version = "1.11.1"
description = "Domichain BPF test program written in Rust"
authors = ["Domichain Maintainers <maintainers@domichain.foundation>"]
repository = "https://github.com/domichain-labs/domichain"
license = "Apache-2.0"
homepage = "https://domichain.com/"
documentation = "https://docs.rs/domichain-bpf-rust-dep-crate"
edition = "2021"

[dependencies]
byteorder = { version = "1", default-features = false }
domichain-program = { path = "../../../../sdk/program", version = "=1.11.1" }
# list of crates which must be buildable for bpf programs
domichain-address-lookup-table-program = { path = "../../../../programs/address-lookup-table", version = "=1.11.1" }

[lib]
crate-type = ["cdylib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
