[package]
name = "libvrf-sys"
version = "0.1.0"
links = "vrf"
build = "build.rs"
edition = "2021"

[dependencies]
libc = "0.2"

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }
pkg-config = "0.3"
