[package]
name = "domichain-send-transaction-service"
version = "1.11.1"
description = "Domichain send transaction service"
authors = ["Domichain Maintainers <maintainers@domichain.foundation>"]
repository = "https://github.com/domichain-labs/domichain"
homepage = "https://domichain.com/"
documentation = "https://docs.rs/domichain-send-transaction-service"
license = "Apache-2.0"
edition = "2021"

[dependencies]
crossbeam-channel = "0.5"
log = "0.4.17"
domichain-client = { path = "../client", version = "=1.11.1" }
domichain-measure = { path = "../measure", version = "=1.11.1" }
domichain-metrics = { path = "../metrics", version = "=1.11.1" }
domichain-runtime = { path = "../runtime", version = "=1.11.1" }
domichain-sdk = { path = "../sdk", version = "=1.11.1" }


[dev-dependencies]
domichain-logger = { path = "../logger", version = "=1.11.1" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
