[package]
name = "domichain-send-transaction-service"
description = "Domichain send transaction service"
documentation = "https://docs.rs/domichain-send-transaction-service"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
crossbeam-channel = { workspace = true }
log = { workspace = true }
domichain-client = { workspace = true }
domichain-measure = { workspace = true }
domichain-metrics = { workspace = true }
domichain-runtime = { workspace = true }
domichain-sdk = { workspace = true }
domichain-tpu-client = { workspace = true }

[dev-dependencies]
domichain-logger = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
