[package]
authors = ["Domichain Maintainers <maintainers@domichain.foundation>"]
edition = "2021"
name = "domichain-store-tool"
description = "Tool to inspect append vecs"
version = "1.11.1"
repository = "https://Domino-Blockchain/domichain"
license = "Apache-2.0"
homepage = "https://domichain.com/"
publish = false

[dependencies]
clap = "2.33.1"
log = { version = "0.4.17" }
domichain-logger = { path = "../../logger", version = "=1.11.1" }
domichain-runtime = { path = "..", version = "=1.11.1" }
domichain-version = { path = "../../version", version = "=1.11.1" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
