[package]
name = "domichain-poh"
description = "Domichain PoH"
documentation = "https://docs.rs/domichain-poh"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
core_affinity = { workspace = true }
crossbeam-channel = { workspace = true }
log = { workspace = true }
domichain-entry = { workspace = true }
domichain-ledger = { workspace = true }
domichain-measure = { workspace = true }
domichain-metrics = { workspace = true }
domichain-runtime = { workspace = true }
domichain-sdk = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
bincode = { workspace = true }
matches = { workspace = true }
rand = { workspace = true }
domichain-logger = { workspace = true }
domichain-perf = { workspace = true }

[lib]
crate-type = ["lib"]
name = "domichain_poh"

[[bench]]
name = "poh"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
