[package]
name = "domichain-vote-program"
description = "Domichain Vote program"
documentation = "https://docs.rs/domichain-vote-program"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true }
log = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
domichain-frozen-abi = { workspace = true }
domichain-frozen-abi-macro = { workspace = true }
domichain-metrics = { workspace = true }
domichain-program = { workspace = true }
domichain-program-runtime = { workspace = true }
domichain-sdk = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
domichain-logger = { workspace = true }
test-case = { workspace = true }

[build-dependencies]
rustc_version = { workspace = true }

[lib]
crate-type = ["lib"]
name = "domichain_vote_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
