/* automatically generated by rust-bindgen 0.60.1 */

extern "C" {
    pub fn vrf_prove(
        proof: *mut ::std::os::raw::c_uchar,
        skpk: *const ::std::os::raw::c_uchar,
        msg: *const ::std::os::raw::c_uchar,
        msglen: ::std::os::raw::c_ulonglong,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn vrf_verify(
        output: *mut ::std::os::raw::c_uchar,
        pk: *const ::std::os::raw::c_uchar,
        proof: *const ::std::os::raw::c_uchar,
        msg: *const ::std::os::raw::c_uchar,
        msglen: ::std::os::raw::c_ulonglong,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn vrf_proof_to_hash(
        hash: *mut ::std::os::raw::c_uchar,
        proof: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
